server:
  port: 8085
  tomcat:
    max-connections: 500
    threads:
      max: 1000
    #最大等待数
    accept-count: 200
  servlet:
    context-path: /base

spring:
  application:
    name: rjsoft
  profiles:
    active: other
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
  #上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

JohnYehyo:
  version: 1.0.0
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 加密公钥
  key: 113813559663B1D1

jasypt:
  encryptor:
    password: JohnYehyo
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

yskj:
  center:
    addr: 172.24.7.189
    port: 9000
  app:
    id: 3f7abd9489c0427b8ade40d1c11f7e6a
  server:
    id: 9f4202f604ed4d38bb13333bb362282f
    name: 应用服务
    homepage: http://localhost:1223/dome02/main
    mainpage: /main
    noFilters: /runstate
    ssoenable: 1
  domain:
    id: e8214062bba411e7813bfa163e94e2b8

  mina:
    name:
    addr:
    port:
  net:
    ip0:
    ip1:

  onlinemsg:
    serverip: 127.0.0.1
    serverport: 9003
    websocketport: 9013
    clienttypeid: scantologin